trigger:
- Azure_CI

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  BROWSERSTACK_TEST_RUN_NAME: $(Build.BuildId)

steps:

# Install .NET 8.0 SDK
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: |
    dotnet --version
  displayName: 'Check .NET SDK version'

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

# Build the solution in release mode
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration) --verbosity detailed'

# Run the tests with more logging and output test results
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration) --verbosity detailed --logger "trx;LogFileName=test-results.trx"'
    publishTestResults: true
    testRunTitle: 'SpecFlow Test Run on BrowserStack'

- script: |
    echo "Setting BrowserStack Test Run Name"
    export BROWSERSTACK_TEST_RUN_NAME=$(Build.BuildId)
    echo "BrowserStack Test Run Name is: $BROWSERSTACK_TEST_RUN_NAME"
  displayName: 'Set BROWSERSTACK_TEST_RUN_NAME'

- task: BrowserStackResults@1
  inputs:
    browserstackProduct: 'automate'
