trigger:
- Azure_CI

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  BROWSERSTACK_TEST_RUN_NAME: $(Build.BuildId)

steps:

- task: BrowserStackConfig@0
  inputs:
    BrowserStackServiceEndPoint: 'browserstack-connection'
    browserstackLocal: true
  displayName: 'Browserstack Configuration'

# Install .NET 8.0 SDK
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet
  displayName: 'Install .NET 8.0 SDK'

# Verify .NET SDK version
- script: |
    dotnet --version
  displayName: 'Verify .NET SDK Version'

# Install NuGet tool
- task: NuGetToolInstaller@1
  displayName: 'Install NuGet Tool'

# Restore NuGet packages
- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'
  displayName: 'Restore NuGet Packages'

# Build the solution in Release mode
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration) --no-restore --verbosity minimal -nowarn:*'
  displayName: 'Build Solution in Release Mode'

# Run the tests and output results
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration) --verbosity minimal --no-restore --logger "trx;LogFileName=test-results.trx" -nowarn:*'
    publishTestResults: true
    testRunTitle: 'SpecFlow Test Run on BrowserStack'
  displayName: 'Run Tests and Publish Results'

  
- task: BrowserStackStopLocal@0
  displayName: 'Stop Browserstack Local'

# Upload results to BrowserStack
- task: BrowserStackResults@1
  inputs:
    browserstackProduct: 'automate'
  displayName: 'Upload Test Results to BrowserStack'
