# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- Azure_CI

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  BROWSERSTACK_TEST_RUN_NAME: $(Build.BuildId)

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'
    
- task: BrowserStackConfig@0
  inputs:
    BrowserStackServiceEndPoint: 'browserstack-connection'
    

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

# Step to run the tests using dotnet test
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/*.csproj'  # Test Project
    arguments: '--configuration $(buildConfiguration) --logger "trx;LogFileName=test-results.trx"'  # Output test results in TRX format
    publishTestResults: true   # Publish test results to Azure DevOps
    testRunTitle: 'SpecFlow Test Run on BrowserStack'

- script: |
    echo "Setting BrowserStack Test Run Name"
    export BROWSERSTACK_TEST_RUN_NAME=$(Build.BuildId)  # Set the environment variable
    echo "BrowserStack Test Run Name is: $BROWSERSTACK_TEST_RUN_NAME"
  displayName: 'Set BROWSERSTACK_TEST_RUN_NAME'
  
- task: BrowserStackResults@1
  inputs:
    browserstackProduct: 'automate'
# Step to build the solution (this includes the test projects)